### ISSUE TITLE
Add "properties.country" to India NSE Debarred List

### ISSUE THREAD

**Issue by rishabhc32** [opensanctions/opensanctions#1201]
**Is your feature request related to a problem? Please describe.**
In current NSE Debarred List, https://www.opensanctions.org/search/?scope=in_nse_debarred, the `properties.country` is array is empty. As NSE is India specific we can hardcode the `country` property for the whole index.

**Describe the solution you'd like**
Hardcode `properties.country` as `in` in "India National Stock Exchange Debarred Entities" Index.

**Comment by pudo** [comment]
Thanks for the recommendation!
