### ISSUE TITLE
Please add the UK Government Financial Sanctions List

### ISSUE THREAD

**Issue by rjelbert** [opensanctions/opensanctions#195]
Hi. I'd like to use your service in conjunction with UK insurance services but it would need to include the UK government Financial Sanctions List.  

See: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets 

I note that they provide a CSV file as one of the formats.

thanks, Richard

**Comment by pudo** [comment]
I think this is the same as https://www.opensanctions.org/datasets/gb_hmt_sanctions/ - we just have it under a slightly outdated name because they switched their messaging a bit in early Februar (and then things got chaotic).

**Comment by rjelbert** [comment]
Thanks for replying Pudo
Not sure yet. The XML based list you mentioned has 2258 total entries but the CSV file I linked to has 14,140 lines/entries. There may be some repetition or variants in the CSV list but that is quite a difference in numbers..,.

**Comment by pudo** [comment]
If I run "remove duplicates" in Excel on the CSV, I get 2186, which actually goes out the other end a bit - but basically I'm splitting out some company hierarchies esp. with regards to Myanmar that are just text fields in the source data...

**Comment by rjelbert** [comment]
Thanks. That is much closer so it's likely to be the same list. I will do some digging around to see if their updates will appear in CSV format at this new location from now on here: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets

**Comment by pudo** [comment]
I'm not sure I understand. Their data is updated usually once a day, if you're interested in the development I'm very happy to share the XML version for the past couple of month (they had a format change at the beginning of February). Closing this for now.
