### ISSUE TITLE
show count of entities and datasets on 2 more pages

### ISSUE THREAD

**Issue by VladimirAlexiev** [opensanctions/opensanctions#200]
Thanks for your very excellent UI! A couple of minor improvements:
* Search results page (eg https://www.opensanctions.org/search/?q=abramovich) shows breakdowns per topic (type) and dataset. But it doesn't show the total number of entities.
* https://www.opensanctions.org/datasets/ shows that Due Diligence List includes 42 data sources and 190,258 targets.
But when you go to its page https://www.opensanctions.org/datasets/default/, it shows breakdown per type and (190,464 total) but not the number of datasets

**Comment by pudo** [comment]
Hello @VladimirAlexiev - sorry for failing to respond to this for a long while. Just two notes on the numbers:

* The total result count is shown near the bottom in the pagination bar, e.g. "1 - 25 of 2817". Unfortunately, for result counts larger than 10k, ElasticSearch doesn't return precise numbers any more, so the result count it only useful below that threshold. 
* I've remodelled the datasets info page a bit, with what I hope is a more useful presentation of the key numbers, and the list of sources. the total number of sources is in the heading of the sources section now. does that look ok to you?

**Comment by VladimirAlexiev** [comment]
* I checked a more common name https://www.opensanctions.org/search/?q=ivanov and I see "1 - 25 of 196", thanks!
* Yes, I see the count in the section Datasets. Thanks!
