### ISSUE TITLE
add ACF Bribetakers List

### ISSUE THREAD

**Issue by VladimirAlexiev** [opensanctions/opensanctions#204]
https://acf.international/ru/bribetakers-list.
A list of about ~500-1000~ 6000 people in 20-30 categories by Navalny's Anti-Сorruption Foundation
The info includes `Name cyrillic, Name eng, DOB, Gender, Description, Tag`.

It's a bunch of PDFs, but I'm sure that if you ask them, they'll provide it in CSV form.

**Comment by pudo** [comment]
https://twitter.com/open_sanctions/status/1519002707163598852

**Comment by VladimirAlexiev** [comment]
copied `fbkinfo, fbkinfo2`

**Comment by VladimirAlexiev** [comment]
asked by email at [info@acf.international](mailto:info@acf.international)

**Comment by pudo** [comment]
We already have feedback from them to say they're planning a machine-readable version this week.

Come join our Slack if you want to coordinate: https://join.slack.com/t/opensanctions/shared_invite/zt-xwnzvht1-9jPnHUwfCzW_Yw9MAG6vTA :)

**Comment by VladimirAlexiev** [comment]
The list was updated: 

Мы обновили санкционные списки!

Благодаря нашим сторонникам мы внесли в них новую информацию, исключили одних фигурантов и добавили других. Работа продолжается — и вы можете принять в ней участие.

Как мы и обещали, работа над списками не закончилась с их публикацией. Мы продолжаем с вашей помощью активно их редактировать, внося правки и уточняя состав включенных в них жуликов и разжигателей войны.

Сегодня мы выложили на сайт обновленные списки, в которых исправили обнаруженные технические ошибки, неизбежные при обработке такого большого объема информации. Также мы исключили из списков некоторых фигурантов, поскольку получили убедительные доказательства того, что они не подпадают под выбранные нами критерии. Одни из таких людей, как мы выяснили, оставили занимаемые должности до начала войны или сразу после. Другие публично выступили против войны. Для нас публичное заявление о неприятии агрессии против Украины — одно из главных оснований для исключения из списков. Более мягкие критерии мы использовали лишь для одной категории: независимых директоров в правлениях государственных компаний. Для них мы посчитали достаточным основанием для исключения сам выход из органов управления после начала войны.

С другой стороны, мы внесли в списки тех разжигателей войны, которые первоначально ускользнули от нашего внимания. Это преимущественно пропагандисты и звезды. Кроме того, мы уточнили информацию по значительному числу фигурантов, добавив даты рождения и отредактировав другие сведения. Часть предложенных изменений еще обсуждается — результаты этой работы будут представлены позже.

Поскольку мы стараемся действовать гласно, открыто предъявляя наши обвинения, мы публикуем полный перечень внесенных изменений. Все они уже включены в обновленные варианты списков. Мы и впредь продолжим эту работу, собирая данные и обновляя списки не реже, чем раз в две недели.

Вся эта работа была бы невозможна без активной помощи наших сторонников. Тысячи людей внимательно изучают информацию, проверяют ее и дополняют. Эта помощь очень важна, и мы за нее благодарны. Если у вас есть замечания или предложения по спискам, пишите нам на почту info@acf.international. При этом, предлагая включить кого-либо в наши санкционные списки, посмотрите, попадает ли этот человек в одну из выделенных нами категорий. Также мы просим прилагать ссылки на публикации, по которым мы можем проверить ваши правки. Это касается и предложений об исключении из списков.

Так победим!

https://acf.international/ru/news/updated-our-sanctions-lists

**Comment by VladimirAlexiev** [comment]
They sent me csv and excel 5d ago, forwarded to your email.
I'll ask they publish such regularly.
