### ISSUE TITLE
aws docker continuously crash

### ISSUE THREAD

**Issue by T-HPeter** [opensanctions/opensanctions#210]
We run opensanctions in AWS and the application continuously crashes after a time. We've tried several solutions, turned off problematic lists, tried to fine-tune the settings, but nothing. The problem is there. Maybe an idea of what to try or what could be the solution?

opensanctions-orig-app-1  | 2022-05-02 07:37:34 [error    ] Crawl failed                   [us_bis_denied] dataset=us_bis_denied
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 174, in _new_conn
opensanctions-orig-app-1  |     conn = connection.create_connection(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 95, in create_connection
opensanctions-orig-app-1  |     raise err
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/connection.py", line 85, in create_connection
opensanctions-orig-app-1  |     sock.connect(sa)
opensanctions-orig-app-1  | socket.timeout: timed out
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
opensanctions-orig-app-1  |     httplib_response = self._make_request(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
opensanctions-orig-app-1  |     self._validate_conn(conn)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
opensanctions-orig-app-1  |     conn.connect()
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 358, in connect
opensanctions-orig-app-1  |     self.sock = conn = self._new_conn()
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 179, in _new_conn
opensanctions-orig-app-1  |     raise ConnectTimeoutError(
opensanctions-orig-app-1  | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f79fa08ec40>, 'Connection to www.bis.doc.gov timed out. (connect timeout=120)')
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
opensanctions-orig-app-1  |     resp = conn.urlopen(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
opensanctions-orig-app-1  |     retries = retries.increment(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 592, in increment
opensanctions-orig-app-1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
opensanctions-orig-app-1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bis.doc.gov', port=443): Max retries exceeded with url: /dpl/dpl.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f79fa08ec40>, 'Connection to www.bis.doc.gov timed out. (connect timeout=120)'))
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 230, in crawl
opensanctions-orig-app-1  |     self.dataset.method(self)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/us_bis_denied.py", line 38, in crawl
opensanctions-orig-app-1  |     path = context.fetch_resource("source.tsv", context.dataset.data.url)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 66, in fetch_resource
opensanctions-orig-app-1  |     with self.http.get(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in get
opensanctions-orig-app-1  |     return self.request('GET', url, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
opensanctions-orig-app-1  |     resp = self.send(prep, **send_kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
opensanctions-orig-app-1  |     r = adapter.send(request, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 507, in send
opensanctions-orig-app-1  |     raise ConnectTimeout(e, request=request)
opensanctions-orig-app-1  | requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.bis.doc.gov', port=443): Max retries exceeded with url: /dpl/dpl.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f79fa08ec40>, 'Connection to www.bis.doc.gov timed out. (connect timeout=120)'))

opensanctions-orig-app-1  | 2022-05-02 08:00:02 [error    ] Crawl failed                   [wd_peppercat_leaders] dataset=wd_peppercat_leaders
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
opensanctions-orig-app-1  |     httplib_response = self._make_request(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
opensanctions-orig-app-1  |     six.raise_from(e, None)
opensanctions-orig-app-1  |   File "<string>", line 3, in raise_from
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
opensanctions-orig-app-1  |     httplib_response = conn.getresponse()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
opensanctions-orig-app-1  |     response.begin()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 316, in begin
opensanctions-orig-app-1  |     version, status, reason = self._read_status()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 285, in _read_status
opensanctions-orig-app-1  |     raise RemoteDisconnected("Remote end closed connection without"
opensanctions-orig-app-1  | http.client.RemoteDisconnected: Remote end closed connection without response
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
opensanctions-orig-app-1  |     resp = conn.urlopen(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
opensanctions-orig-app-1  |     retries = retries.increment(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 550, in increment
opensanctions-orig-app-1  |     raise six.reraise(type(error), error, _stacktrace)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 769, in reraise
opensanctions-orig-app-1  |     raise value.with_traceback(tb)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
opensanctions-orig-app-1  |     httplib_response = self._make_request(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
opensanctions-orig-app-1  |     six.raise_from(e, None)
opensanctions-orig-app-1  |   File "<string>", line 3, in raise_from
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
opensanctions-orig-app-1  |     httplib_response = conn.getresponse()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
opensanctions-orig-app-1  |     response.begin()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 316, in begin
opensanctions-orig-app-1  |     version, status, reason = self._read_status()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 285, in _read_status
opensanctions-orig-app-1  |     raise RemoteDisconnected("Remote end closed connection without"
opensanctions-orig-app-1  | urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 230, in crawl
opensanctions-orig-app-1  |     self.dataset.method(self)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/wd_peppercat.py", line 37, in crawl
opensanctions-orig-app-1  |     crawl_qid(context, qid, country)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/wd_peppercat.py", line 14, in crawl_qid
opensanctions-orig-app-1  |     entity_to_ftm(
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/entity.py", line 190, in entity_to_ftm
opensanctions-orig-app-1  |     apply_claim(context, proxy, claim, depth, seen)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/entity.py", line 94, in apply_claim
opensanctions-orig-app-1  |     value = claim.text(context)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/claim.py", line 30, in text
opensanctions-orig-app-1  |     return snak_value_to_string(context, self.value_type, self._value)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/value.py", line 29, in snak_value_to_string
opensanctions-orig-app-1  |     return get_label(context, value.get("id"))
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/api.py", line 36, in get_label
opensanctions-orig-app-1  |     data = wikibase_getentities(
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/api.py", line 22, in wikibase_getentities
opensanctions-orig-app-1  |     return context.fetch_json(WD_API, params=params, cache_days=cache_days)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 120, in fetch_json
opensanctions-orig-app-1  |     text = self.fetch_text(*args, **kwargs)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 108, in fetch_text
opensanctions-orig-app-1  |     response = self.fetch_response(url, headers=headers, auth=auth)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 82, in fetch_response
opensanctions-orig-app-1  |     response = self.http.get(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in get
opensanctions-orig-app-1  |     return self.request('GET', url, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
opensanctions-orig-app-1  |     resp = self.send(prep, **send_kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
opensanctions-orig-app-1  |     r = adapter.send(request, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 501, in send
opensanctions-orig-app-1  |     raise ConnectionError(err, request=request)
opensanctions-orig-app-1  | requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

opensanctions-orig-app-1  | 2022-05-02 08:50:40 [error    ] Crawl failed                   [wd_peppercat_legislators] dataset=wd_peppercat_legislators
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 449, in _make_request
opensanctions-orig-app-1  |     six.raise_from(e, None)
opensanctions-orig-app-1  |   File "<string>", line 3, in raise_from
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 444, in _make_request
opensanctions-orig-app-1  |     httplib_response = conn.getresponse()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
opensanctions-orig-app-1  |     response.begin()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 316, in begin
opensanctions-orig-app-1  |     version, status, reason = self._read_status()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/http/client.py", line 277, in _read_status
opensanctions-orig-app-1  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/socket.py", line 704, in readinto
opensanctions-orig-app-1  |     return self._sock.recv_into(b)
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
opensanctions-orig-app-1  |     return self.read(nbytes, buffer)
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/ssl.py", line 1099, in read
opensanctions-orig-app-1  |     return self._sslobj.read(len, buffer)
opensanctions-orig-app-1  | socket.timeout: The read operation timed out
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 440, in send
opensanctions-orig-app-1  |     resp = conn.urlopen(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 785, in urlopen
opensanctions-orig-app-1  |     retries = retries.increment(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 550, in increment
opensanctions-orig-app-1  |     raise six.reraise(type(error), error, _stacktrace)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/packages/six.py", line 770, in reraise
opensanctions-orig-app-1  |     raise value
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
opensanctions-orig-app-1  |     httplib_response = self._make_request(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 451, in _make_request
opensanctions-orig-app-1  |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
opensanctions-orig-app-1  |     raise ReadTimeoutError(
opensanctions-orig-app-1  | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.wikidata.org', port=443): Read timed out. (read timeout=120)
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | During handling of the above exception, another exception occurred:
opensanctions-orig-app-1  |
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 230, in crawl
opensanctions-orig-app-1  |     self.dataset.method(self)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/wd_peppercat.py", line 37, in crawl
opensanctions-orig-app-1  |     crawl_qid(context, qid, country)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/wd_peppercat.py", line 14, in crawl_qid
opensanctions-orig-app-1  |     entity_to_ftm(
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/entity.py", line 190, in entity_to_ftm
opensanctions-orig-app-1  |     apply_claim(context, proxy, claim, depth, seen)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/entity.py", line 94, in apply_claim
opensanctions-orig-app-1  |     value = claim.text(context)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/claim.py", line 30, in text
opensanctions-orig-app-1  |     return snak_value_to_string(context, self.value_type, self._value)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/value.py", line 29, in snak_value_to_string
opensanctions-orig-app-1  |     return get_label(context, value.get("id"))
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/api.py", line 36, in get_label
opensanctions-orig-app-1  |     data = wikibase_getentities(
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/wikidata/api.py", line 22, in wikibase_getentities
opensanctions-orig-app-1  |     return context.fetch_json(WD_API, params=params, cache_days=cache_days)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 120, in fetch_json
opensanctions-orig-app-1  |     text = self.fetch_text(*args, **kwargs)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 108, in fetch_text
opensanctions-orig-app-1  |     response = self.fetch_response(url, headers=headers, auth=auth)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 82, in fetch_response
opensanctions-orig-app-1  |     response = self.http.get(
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 542, in get
opensanctions-orig-app-1  |     return self.request('GET', url, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 529, in request
opensanctions-orig-app-1  |     resp = self.send(prep, **send_kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 645, in send
opensanctions-orig-app-1  |     r = adapter.send(request, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 532, in send
opensanctions-orig-app-1  |     raise ReadTimeout(e, request=request)
opensanctions-orig-app-1  | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.wikidata.org', port=443): Read timed out. (read timeout=120)
opensanctions-orig-app-1  | {'NonLatinScriptLanguage': 'Bosnian', 'NonLatinScriptType': 'Cyrillic'}
opensanctions-orig-app-1  | Traceback (most recent call last):
opensanctions-orig-app-1  |   File "/usr/local/bin/opensanctions", line 33, in <module>
opensanctions-orig-app-1  |     sys.exit(load_entry_point('opensanctions', 'console_scripts', 'opensanctions')())
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1128, in __call__
opensanctions-orig-app-1  |     return self.main(*args, **kwargs)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1053, in main
opensanctions-orig-app-1  |     rv = self.invoke(ctx)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1659, in invoke
opensanctions-orig-app-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1395, in invoke
opensanctions-orig-app-1  |     return ctx.invoke(self.callback, **ctx.params)
opensanctions-orig-app-1  |   File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 754, in invoke
opensanctions-orig-app-1  |     return __callback(*args, **kwargs)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/cli.py", line 58, in run
opensanctions-orig-app-1  |     run_pipeline(dataset, threads=threads)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/processing.py", line 32, in run_pipeline
opensanctions-orig-app-1  |     _compute_futures(futures)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/processing.py", line 16, in _compute_futures
opensanctions-orig-app-1  |     future.result()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result
opensanctions-orig-app-1  |     return self.__get_result()
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
opensanctions-orig-app-1  |     raise self._exception
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
opensanctions-orig-app-1  |     result = self.fn(*self.args, **self.kwargs)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/core/context.py", line 230, in crawl
opensanctions-orig-app-1  |     self.dataset.method(self)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/ua_nsdc_sanctions.py", line 90, in crawl
opensanctions-orig-app-1  |     crawl_physical(context)
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/ua_nsdc_sanctions.py", line 44, in crawl_physical
opensanctions-orig-app-1  |     data = json_resource(context, PHYSICAL_URL, "physical")
opensanctions-orig-app-1  |   File "/opensanctions/opensanctions/crawlers/ua_nsdc_sanctions.py", line 17, in json_resource
opensanctions-orig-app-1  |     return json.load(fh)
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/json/__init__.py", line 293, in load
opensanctions-orig-app-1  |     return loads(fp.read(),
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
opensanctions-orig-app-1  |     return _default_decoder.decode(s)
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
opensanctions-orig-app-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
opensanctions-orig-app-1  |   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
opensanctions-orig-app-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
opensanctions-orig-app-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pudo** [comment]
No idea. Does this thing have network connectivity? 

Do you have a particular reason for not using the OS releases?

**Comment by T-HPeter** [comment]
Thanks for the quick response!

We are also running the version of the OS that is in the repo (ubuntu: 21.04). We also tried a newer version (ubuntu: 22.04). The error persisted in all cases.

However, if you run (docker run ....) a postgres database and the pudo / opensanctions docker image that communicates with localhoston, it works fine in all cases.

However, everything else works in our aws network, except it doesn't.

We have tried on different machines, in different ways, the problem persists.

**Comment by T-HPeter** [comment]
Can you help? Other new information?

**Comment by pudo** [comment]
All I can do is to confirm that it works on both my server and my local computer without networking issues. So the URLs being accessed are correct, and the code works. It thus must be some aspect of the deployment: firewall, networking settings, blocks? How often are you running this - if you do it too often, maybe you get blocked?
