### ISSUE TITLE
Ukraine EDR enrichment 

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#217]
Let's pull in subsidiaries of companies listed on NSDC.

**Comment by VladimirAlexiev** [comment]
hey @pudo I'm pretty sure this is https://sanctions.nazk.gov.ua/en, https://sanctions.nazk.gov.ua/en/sanction-lists/.
Some people are matching this list to Wikidata: https://www.wikidata.org/wiki/Topic:X1tso7h1p6hf3ezz, https://mix-n-match.toolforge.org/#/catalog/5404.

**Comment by pudo** [comment]
As you mention on the topic, we do have the NAZK list in OpenSanctions. The EDR would just be the normal Ukrainian companies registry, so if NAZK lists "Sevastopol Bla Corp.", we'd also get its owners and perhaps even a subsidiary company (this is all grey theory because the data quality of the EDR is .... well, it's a lot of messy strings). 

Here's the parser to the extent that I have it: https://github.com/alephcommons/ua-edr 
And the draft dataset in OSa: https://www.opensanctions.org/datasets/ua_edr/
