### ISSUE TITLE
Crash after crawling when one of the dataset threw an Exception

### ISSUE THREAD

**Issue by skrafft** [opensanctions/opensanctions#222]
Hi,

I've been trying to use the docker container to run all crawlers and the process crashes after the crawling and before the export.
I narrowed the problem to this specific code in https://github.com/opensanctions/opensanctions/blob/main/opensanctions/processing.py#L16

```
def _compute_futures(futures: List[Future]):
    wait(futures)
    for future in futures:
        future.result()
```

It seems that future.result() throws the exception that was raised to the thread previously.
Reading the doc and trying, I think this specific line is useless as crawlers are not supposed to return a result.

As I was not sure, I ended up catching all Exceptions returned by future.result() which works:
```
def _compute_futures(futures: List[Future]):
    wait(futures)
    for future in futures:
        try:
            future.result()
        except Exception as error:
            print('Ignoring thread result error')
```

@pudo , what do you think ?

I can make a pull request for the fix if needed.

**Comment by pudo** [comment]
Hi! Thanks for raising this issue. The rationale for having threads raise their exceptions is to "provoke" a non-zero exit code when one of the crawls has failed, as an indication that all is not good and possible next steps in the ETL pipeline should be aborted. In fact, that's also the only reason the `for` loop exists: by default, the exceptions would be swallowed by the ThreadPoolExecutor. So the easiest work-around is to just get rid of the loop.

I guess I'm a tiny bit uncertain about the "correct" behaviour here: should exceptions just be passed over? Can you tell me something about your execution model and what would be most helpful there?

(For opensanctions.org, I'm running the builds via GitHub Actions but on a custom server - which also holds the database. Every crawler is set up as it's own build task feeding into the export stage.)

**Comment by skrafft** [comment]
HI! Thanks for the answer. By reading the document, I thought that `opensanctions run` was to run all crawlers, ignore errors and export all data. This was obviously wrong. If I want to do this, the right way would be to run `opensanctions crawl` and then `opensanctions export`. I'll close this ticket as I think it's just me that misunderstood the documentation.

**Comment by pudo** [comment]
I've reflected this here: #225.
