### ISSUE TITLE
Change in CLI commands

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#225]
I've seen a few bug reports recently that were based around the fact that `opensanctions run` never completes. This is caused by the fact that at any one time, at least one of the crawlers will throw an error (it's basically considered normal).

What happens is this: `opensanctions run` will first run `opensanctions crawl` and then, if successful, run `opensanctions export`. But it's never successful, so no export is generated. This doesn't happen in the opensanctions.org production because each crawler is run separately in a GitHub Action and the exports are somewhat separate. 

So what to do? I think I'll get rid of `opensanctions run`. This way, people can be explicit in deciding to run: 

* `opensanctions crawl; opensanctions export` - if they want to export irrespective of whether the run was a success
* `opensanctions crawl && opensanctions export` - for a "strict" mode

This is not much less convenient, but more explicit.

**Comment by pudo** [comment]
I've also added a `clear-workdir` command, which should be run before the other parts of the pipeline to get rid of cached source data:

* `opensanctions clear-workdir; opensanctions crawl; opensanctions export`

**Comment by pudo** [comment]
Closing, no action.

**Comment by LandonStewart** [comment]
Please also update install.rst and the Makefile since `opensanctions run` isn't a thing anymore.
