### ISSUE TITLE
Upcoming schema changes notification (draft)

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#226]
I'm drafting this email in public, because why not. 

Dear OpenSanctions users,

I'm writing to inform all of you of some planned changes to the OpenSanctions data schema. The outlined changes are additive and - to the best of my understanding - none of them will break existing functions. If you are using OpenSanctions by deploying `yente`, I would suggest deploying the latest version of the application some time in the next three weeks. 

* Images 
* Addresses inline (duplication)
* Posts

**Comment by ppseprus** [comment]
Thanks for the heads-up, @pudo! ;)

![](https://media.giphy.com/media/xHMIDAy1qkzNS/giphy.gif)
