### ISSUE TITLE
request for Dutch sanction list

### ISSUE THREAD

**Issue by janjjansen** [opensanctions/opensanctions#230]
there are more national sanction lists that could be very useful.
I see belgian sanction list: be_fod_sanctions, and french sanction list: fr_tresor_gels_avoir

There is also a Dutch sanction list https://www.government.nl/documents/reports/2016/01/15/national-terrorism-list
in ods format. (https://www.government.nl/binaries/government/documenten/reports/2016/01/15/national-terrorism-list/eng-terrorismelijst.ods).

**Comment by pudo** [comment]
That would be a cool addition, and the data looks simple but useable. I've written an ODS parser before here: 

https://github.com/alephdata/ingest-file/blob/main/ingestors/tabular/ods.py#L24-L73

Maybe we could use that library (`odf`) and even make an iterate-over-ODS-rows helper?

**Comment by pudo** [comment]
Fixed in #234.

**Comment by pudo** [comment]
> Can you not have sanctions on a person? It must be an entity?

No, a person is just a special sub-type of LegalEntity (that's just a broad term for people, companies etc.)

**Comment by pudo** [comment]
It's live here: https://www.opensanctions.org/datasets/nl_terrorism_list/
