### ISSUE TITLE
how to submit entity "merge requests"

### ISSUE THREAD

**Issue by VladimirAlexiev** [opensanctions/opensanctions#232]
I'm pretty sure these two are the same guy
- https://www.opensanctions.org/entities/Q112194249/: military commander, member of Security Council
- https://www.opensanctions.org/entities/ru-inn-645205630830/: same 3 names, and [Salyut JSC](https://www.opensanctions.org/entities/NK-5edZFYeL5teafSPzMxGr7Y/) sounds very much like a military vendor.

I've reflected this in the "external identifiers" of the Wikidata item https://www.wikidata.org/wiki/Q112194249:
- the first 4 are from the first OpenSanctions entry
- the last one is from the second OpenSanctions entry

My question is: how can you use the fact that all these IDs are collapsed in the same WD item, to merge the two OpenSanctions entries?
Do we need to send you some ping, or you do that periodically?

**Comment by pudo** [comment]
To be honest, I haven't yet figured out how to take merge suggestions more systematically. One of my near-term plans is to make the merge list happen inside of SQL, which would open up the option of making a web UI for it down the road - but that doesn't solve the editorial issue of how to define the threshold.

For example, with the individual you named above, I wouldn't normally make the link on that basis. I'd either want Salyut to be mentioned in the Ukrainian records, or I'd need a birth day, INN or something like that as a secondary indicator. Name alone is too icky...

(FWIW, I just got a nice merge suggestion spreadsheet from the UA NAZK, but still busy reviewing these. It takes a few days, but then I know it's all double-checked. In general, it's incredibly valuable to report cases where you think the merge may be *false* - the missing ones I'll get to, automatically, but the incorrect ones are the ones that keep me up at night).

**Comment by VladimirAlexiev** [comment]
I agree that a name like Ivan Ivanovich doesn't allow a confident match. But the 3 names of Bushuev are fairly unique.

Speaking of Salyut, how can I link
https://www.opensanctions.org/entities/NK-5edZFYeL5teafSPzMxGr7Y/
to https://www.wikidata.org/wiki/Q1949319 ?

Wikidata's Mix-n-Match is very useful to crowdsource this kind of work. Eg see https://mix-n-match.toolforge.org/#/catalog/5404

**Comment by pudo** [comment]
@VladimirAlexiev I would ask you to allow me to be conservative in merging entities. I want OpenSanctions to be viable as a business as well as an open data resource - which requires it being reliable - and I also need to navigate the reputational implications of false merges.

Just to be super clear: I have no interest in merging up companies in OpenSanctions with company items in Wikidata. The way that Wikidata will define in the "this is Coca Cola" sense, whereas when you're dealing with investigative reporting or due diligence, that's just not OK. Plus there are tons of existing databases that manage company data very well, there is absolutely no need for Wikidata to do this.

This is not a Wikidata staging project. If that doesn't work for you, please feel free to fork.

**Comment by VladimirAlexiev** [comment]
@pudo Wikidata is not a company database, and you are right that it does not distinguish between different closely related legal bodies. I'm not sure what is the goal of OS when it comes to companies: would it link closely related enterprises, or stick to individual trade register registrations.

You are right that I was hasty, https://www.wikidata.org/wiki/Q1949319 is not the Salyut in question, and maybe even https://www.wikidata.org/wiki/Q48940402 is not.

Of course, it's up to you to decide whether and what merge contributions you accept in OS. I take it from your response that you'd only take contributions from established data partners. Cheers!
