### ISSUE TITLE
Add "FBI Most Wanted"

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#235]
cf. https://www.fbi.gov/wanted 

@janjjansen Can I tempt you somehow into giving this a try? 😺

**Comment by brammittendorff** [comment]
You could just use this URL: 

```
https://www.fbi.gov/wanted/fugitives/@@castle.cms.querylisting/f7f80a1681ac41a08266bd0920c9d9d8?_layouteditor=true&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fcac%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fcei%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fcyber%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fmurders%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fadditional%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fcounterintelligence%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fwcc%3A%3A-1&query.i:records=path&query.o:records=plone.app.querystring.operation.string.absolutePath&query.v:records=%2Fwanted%2Fhuman-trafficking%3A%3A-1&query.i:records=portal_type&query.o:records=plone.app.querystring.operation.selection.any&query.v:records=[u%27Person%27]&query.i:records=review_state&query.o:records=plone.app.querystring.operation.selection.any&query.v:records=[u%27published%27]&display_fields=(%27image%27%2C)&available_tags=(u%27Crimes+Against+Children%27%2C+u%22Cyber%27s+Most+Wanted%22%2C+u%27White-Collar+Crime%27%2C+u%27Counterintelligence%27%2C+u%27Human+Trafficking%27%2C+u%27Criminal+Enterprise+Investigations%27%2C+u%27Violent+Crime+-+Murders%27%2C+u%27Additional+Violent+Crimes%27)&display_type=wanted-feature-grid&sort_on=modified&limit=40&page=1
```

And change the parameter `&page=1` ++ until `Results: 368 Items` 368 / 40 = 9.2 so +/- 10 times.

**Comment by brammittendorff** [comment]
I will start this one then!

**Comment by pudo** [comment]
Oh that's amazing! I was looking at it again yesterday but haven't written any code yet :)

**Comment by brammittendorff** [comment]
![Screenshot from 2022-11-10 17-27-09](https://user-images.githubusercontent.com/7221583/201151560-c2b4d5a4-cb0e-4403-a2d0-a6bc4a945410.png)

**Comment by pudo** [comment]
Uuuuh lovely. I'm super keen to help with the alignment stuff ("entity.add()") and if there's any issues with picking apart the HTML!

**Comment by brammittendorff** [comment]
Here you go, please let me know if I need to change stuff... It's my first commit :dancers: so most likely I do something wrong.
https://github.com/opensanctions/opensanctions/pull/247/files

**Comment by pudo** [comment]
I'm doing a little once-over on it now, please don't take this the wrong way. Some changes:

* Not storing the `source_x.html` pages - that only makes sense if the build would be reproducible from them. 
* Adding some more breakage points so that when errors happen, they show up in our logging :) 

Anyway, I think this is ready for prime time!

**Comment by brammittendorff** [comment]
Great I will take a look at your feedback and see what I can do.

**Comment by brammittendorff** [comment]
This means the excel can also be set to `done` right? https://docs.google.com/spreadsheets/d/1zHP91a-KT-MW-3s2Xb9-wPVhxTiPO1ZqJ90v4COswRY/edit#gid=0

**Comment by pudo** [comment]
The index is still updating, but it's now here: https://www.opensanctions.org/datasets/us_fbi_most_wanted/
