### ISSUE TITLE
Единая база данных

### ISSUE THREAD

**Issue by Leonid1912** [opensanctions/opensanctions#237]
Добрый день!

Спасибо большое Вам за такой проект

Хотел бы уточнить, планируется ли (или уже есть) сбор всех данные в единый "файл"?
Дело в том, что я хочу составить для своих сотрудников программку, наполненную Вашими данными, но, это проблематично, когда более 100 источников

В итоге я бы хотел создать скрипт, который будет раз в сутки обновлять данные с Вашего сайта и переводить в мою программу, а дальше мои сотрудники уже по названию будет их искать

**Comment by pudo** [comment]
Hello! Yes, OpenSanctions does generate a single file to include the data from all the sources. What's special about this is that we're merging together entities from the different lists into a single profile (e.g. an individual mentioned on 20 lists would show up once, not 20 times). You can either generate the combined dataset (called "default") by running this code base, or by licensing the data from OpenSanctions.org, where it is updated every day: 

https://www.opensanctions.org/datasets/default/#download
https://www.opensanctions.org/licensing/

**Comment by pudo** [comment]
Closing for no action.
