### ISSUE TITLE
Compute daily deltas

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#238]
We want to be able to produce a data file that just contains the changed entities day to day. The file also needs to give information regarding entities that have been deleted since the previous day. 

How? 
* Compute a hash for each entity on day 1 
* Compute a hash for each entity on day 2
* Export the difference between both hash sets.

**Comment by pudo** [comment]
Playing with this here after renewed customer interest: https://github.com/opensanctions/data-quality/blob/main/delta.py 

This seems to be working well, albeit there will be some weirdness with the fact that data is released multiple times a day.

**Comment by pudo** [comment]
Files are now being generated under this URL structure:

* https://data.opensanctions.org/contrib/delta/20221116/sanctions.delta.json
* https://data.opensanctions.org/contrib/delta/20221116/default.delta.json

**Comment by etlel** [comment]
@pudo The link in the [FAQ](https://www.opensanctions.org/docs/faq/) to the "[public data pipeline](https://github.com/opensanctions/opensanctions/actions/workflows/production.yml)" is broken.

**Comment by pudo** [comment]
@etlel Nice catch. Removed the link (data pipeline is now running privately because it's using github hosted runners to be able to work properly).

**Comment by pudo** [comment]
This has been implmented and is running pretty stable right now: https://www.opensanctions.org/faq/80/bulk-deltas/
