### ISSUE TITLE
"Identification" objects under "identificiation" key

### ISSUE THREAD

**Issue by wblondel** [opensanctions/opensanctions#240]
Hi,

While parsing a dataset I noticed that "Person" objects can have "Identification" objects, and those are in the "identificiation" key.

Is this spelling mistake intentional?

This mistake is also in the documentation: https://www.opensanctions.org/reference/ (7 results for "identificiation")

Thanks!

**Comment by pudo** [comment]
aaargh. yes it's a typo. we'll need to fix it. can you implement it on your end to handle both for now, with the correct spelling taking precedence?

**Comment by wblondel** [comment]
Yes, that is what I did. 😄 
Thanks for the quick answer!

**Comment by pudo** [comment]
And, gone.
