### ISSUE TITLE
Add more wanted lists to the Data sources roadmap

### ISSUE THREAD

**Issue by brammittendorff** [opensanctions/opensanctions#251]
Countries in Europe:

- IT: https://www.interno.gov.it/it/ministero/dipartimenti/dipartimento-pubblica-sicurezza/direzione-centrale-polizia-criminale/direzione-centrale-polizia-criminale-elenco-dei-latitanti-massima-pericolosita
- ES (GUARDA): https://www.guardiacivil.es/en/colaboracion/buscados/index.html
- ES (POLICIA): https://www.policia.es/_es/colabora_masbuscados.php#
- PL: https://ksp.policja.gov.pl/pz/scigani
- NL: https://www.politie.nl/gezocht-en-vermist/nationale-opsporingslijst
- BE: https://www.police.be/5998/en/wanted/most-wanted

- BR: http://procurase.seguranca.mg.gov.br/
- BR: https://procurados.pb.gov.br/
- BR: https://www.gov.br/mj/pt-br/assuntos/sua-seguranca/operacoes-integradas/procurados
- BR: https://www.policiacivil.sp.gov.br/portal/faces/pages_home/servicos/procuradosJustica
- BR: https://disquedenuncia181.es.gov.br/procurados
- BR: https://www.sds.pe.gov.br/procurados
- BR: https://www.sap.ce.gov.br/procurados-pela-justica/
- BR: https://www.ssp.ma.gov.br/disque-denuncia/procurados/
- BR: https://www.seap.pa.gov.br/procurados
- BR: http://www.policiacivil.am.gov.br/procurados/
- BR: https://policiacivil.se.gov.br/procurados/

**Comment by pudo** [comment]
Just came across: https://qamqor.gov.kz/criminals

**Comment by brammittendorff** [comment]
> Just came across: https://qamqor.gov.kz/criminals

Nice one!

**Comment by brammittendorff** [comment]
Let's close this, I think you have added a few that you are interested in right?

**Comment by pudo** [comment]
Most of them are in the sources sheet now, closing.
