### ISSUE TITLE
Classification PEP data according to FATF PEP risk levels

### ISSUE THREAD

**Issue by muhammetcagatay** [opensanctions/opensanctions#267]
https://www.fatf-gafi.org/en/publications/Fatfrecommendations/Peps-r12-r22.html

**Comment by muhammetcagatay** [comment]
It's a feature that I think could be added to open sanction. Because I think PEP risk classification is important for people using the data here. In addition, the classification is stated as a feature in each person?  I couldn't find this classification variable.

**Comment by pudo** [comment]
What kind of classification are you referring to, specifically?

**Comment by muhammetcagatay** [comment]
for example, urban assemblies members are at low risk. Heads of countries are at high risk. You can access more detailed information from this resource https://sanctionscanner.com/knowledge-base/politically-exposed-person-pep-56

**Comment by brammittendorff** [comment]
It would be nice to do this in the future, but it will not be a generic solution for all.

We should first add more data sources because we are still missing a lot of countries. Maybe add images to people or street images to companies. And enrich our data more.

So this would be nice for a future idea but in my humble opinion, not a high priority issue for me to code right now.

**Comment by pudo** [comment]
I'm actually working on this a bit; the way we do it mainly relates to Wikidata, which links people to positions they hold or have held. When we crawl Wikidata for PEPs it's based on a list of "monitored positions" right now, and these positions are what would need to be tagged into internal/external. Right now they're tagged sub-national/national/international. So it may make sense to classify each political post alongside the following axes:

* Level of government (national, sub-national)
* FATF risk level (internal, external)
* Branch of government (I'm just curious and think this could make it easier to browse)

Exposing this classification system to the public is a blocked on building a login system for the web site (I've asked auth0 for a startup account, waiting....).

**Comment by pudo** [comment]
This is done to a really nice level of detail now: https://www.opensanctions.org/docs/pep/methodology/ - respond with any feedback on this, please :)
