### ISSUE TITLE
Data on politically exposed persons and their associates in the Czech republic

### ISSUE THREAD

**Issue by opop999** [opensanctions/opensanctions#290]
Hi, 
You might be interested in the dataset maintained by the Czech non-profit[ *Hlídač státu*](https://www.hlidacstatu.cz/osoby/), which contains comprehensive coverage of political actors and their associates. The dataset can also be queried through REST API (`/api/v2/osoby` endpoint). 

It is free for non-commercial use but also offers a commercial license. They also have some other datasets of potential interest, such as[ *Rejstřík trestů právnických osob*](https://www.hlidacstatu.cz/data/Index/rejstrik-trestu-pravnickych-osob) (Register of penalties of legal entities). 

Finally, I can also recommend R's library [*hlidacr*](https://github.com/skvrnami/hlidacr), which eases the work with the API.

I hope this helps!

**Comment by pudo** [comment]
This is really cool, thanks so much for sharing these hints! Do you work with Hlídač státu? Do you know of anyone inside the organization that would ask to check if they'd be OK with us pulling in their data?

**Comment by opop999** [comment]
Hi, you have a fascinating and socially important project, so I am glad this could help you. I used their datasets when working on a non-profit project on Czech elections monitoring for _Transparency International Czech Republic_. I had multiple contacts with the team of _Hlídač Státu_, who helped me when I encountered issues with the API.

So I guess the fastest route would be to contact directly [Michal Bláha](https://texty.hlidacstatu.cz/team/) and cc Lenka Stryalová and Petr Suchý. Optionally you could mention you got the contact from me (Ondrej Pekacek / TI CZ).

**Comment by jbothma** [comment]
Looks like it's CC BY so as long as we link to the license on the dataset description, we should be good.

**Comment by jbothma** [comment]
Actually I'm not sure if our commercial licensing is compatible with

**Comment by pudo** [comment]
Sent them an email to clarify.

**Comment by pudo** [comment]
Got a nice reply from their lead: 

> Our licence is really CC by 3.0. Full text of the licence is (in german) here: https://creativecommons.org/licenses/by/3.0/de/legalcode
> However, we are thinking about changing the license to the same license you are using as of January 1, 2024.
> We will make this decision by the end of November 2023.
> Answer to your question: you can use our data with a link, but please be aware of a possible change to the same license you are using.

So let's wait until the end of next month and figure out how to proceed then :)
