### ISSUE TITLE
Import new lists for Kazakhstan

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#303]
It looks like Kazakhstan shut down its old list web site and now offers three separate XML files here: 

https://websfm.kz/terrorism

Files:
* Persons: https://api.websfm-pilot.afmrk.gov.kz/v1/sanctions/sanction-terrorist-old/xml_category_1/?status=acting 
* Organizations: https://api.websfm-pilot.afmrk.gov.kz/v1/sanctions/sanction-terrorist-old/xml_category_2/?status=acting 
* Proliferation list: https://api.websfm-pilot.afmrk.gov.kz/v1/sanctions/sanction-weapon-old/xml/

**Comment by jbothma** [comment]
@pudo I think the first list is done in #311 

The third one looks like it might be the UN security council list - do you know differently? Reckon there's a source with more detail for this? Or should I just grab this and document as I see it here?

![Screenshot_2023-06-23_17-23-42](https://github.com/opensanctions/opensanctions/assets/235801/4523b1d6-61f6-4b54-9a76-cd4417400bff)
![Screenshot_2023-06-23_17-27-27](https://github.com/opensanctions/opensanctions/assets/235801/9f88c8ff-314a-41fc-b9bc-c95fe3bcdad6)

![Screenshot_2023-06-23_17-23-26](https://github.com/opensanctions/opensanctions/assets/235801/460dff2f-8e64-4f34-862a-c7e762f0493b)
![Screenshot_2023-06-23_17-27-43](https://github.com/opensanctions/opensanctions/assets/235801/c2ee8e8f-e0f5-4845-9c91-7fdc1fe4f35c)

**Comment by pudo** [comment]
yeah this looks like the UN SC consolidated list which we're already importing 6 times over -- so let's skip!

**Comment by jbothma** [comment]
that was quick!

for the category 2 list, is it worth doing a separate dataset to distinguish "participating in terrorism" from "financing terrorism"?
![Screenshot_2023-06-23_17-29-02](https://github.com/opensanctions/opensanctions/assets/235801/90bd58ee-59e2-4528-85dd-3ddda1b0b005)

**Comment by pudo** [comment]
I think that could be handled by doing a different `sanction.add("program", "....")` in each half of the crawler script? And make sure that we go from `source.xml` to two different file names :)
