### ISSUE TITLE
ingest Wagner members and maybe more from Myrotvorets

### ISSUE THREAD

**Issue by VladimirAlexiev** [opensanctions/opensanctions#325]
https://myrotvorets.center/criminal/ has a bunch of detailed records of Russian soldiers, PMC Wagner members and other criminals.
There are detailed records with photos, army unit, passport data, etc: eg see https://myrotvorets.center/criminal/feofilaktov-aleksej-pavlovich/ .

I don't know whether this list is available as CSV, but 4k records of PMC Wagner members are available:
- https://myrotvorets.news/spysok-naemnykov-y-terrorystov-chvk-va/ (page)
- https://myrotvorets.news/wp-content/uploads/2021/12/vagner4000.zip (CSV)
- https://myrotvorets.news/wp-content/uploads/2021/12/vagner4000.xlsx (Excel)

The excel has 3 columns of names per person. For some persons, there are additional rows that give additional names. You can identify them by the URL of the detailed information. Eg all these rows mention the same detailed page as cited above:
- Feofilaktov Aleksej Pavlovich	Феофилактов Алексей Павлович	Феофілактов Олексій Павлович
- Feofilaktov Aleksej Pavlovich	Феофилактов Алексей Николаевич	Феофілактов Олексій Павлович
- Feofilaktov Aleksej Pavlovich	Феофилактов Алексей Павлович	Феофілактов Олексій Миколайович
- Feofilaktov Aleksej Nikolaevich	Феофилактов Алексей Павлович	Феофілактов Олексій Павлович

Number of total and deduplicated rows (13.4% duplication):
```
# wc -l vagner4000.csv
4496 vagner4000.csv

# cut -d, -f6 vagner4000.csv | sort | uniq | wc -l
3965
```

**Comment by VladimirAlexiev** [comment]
Commented at https://myrotvorets.news/spysok-naemnykov-y-terrorystov-chvk-va/ :

> I posted a task https://github.com/opensanctions/opensanctions/issues/325 to ingest this list to https://www.opensanctions.org/. Two questions:
>- What is the total number at https://myrotvorets.center/criminal/?
>- Are there more CSVs that list people from these pages?

**Comment by pudo** [comment]
Here we are: https://www.opensanctions.org/datasets/ru_myrotvorets_wagner/ 

It would of course be lovely to get more detail in the CSV (e.g. birth place, specific accused crimes)

**Comment by VladimirAlexiev** [comment]
Thanks @pudo ! 

Could you add links "member" to https://www.opensanctions.org/entities/Q36597284/ ?

Can you fix these IDs (they are broken links due to some tech problems in WD):
- Q120706615 -> Q120851450 (ZHemchuzhnyj Andrej Valterovich)
- Q120712921 -> Q120854799 (Ermolaev Aleksandr Elizarovich)

On the other hand, we hope to add OS ID to WD soon.

>  get more detail in the CSV (e.g. birth place, specific accused crimes)

That'd be hard since the myrotvorets descriptions are free-text and show great variety.
(There's no birth place, but there is Address)

**Comment by daniilzheler** [comment]
Как вы парсили сайт?
