### ISSUE TITLE
Data on PEPs in Cuba

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#329]
We've been invited to crawl this: https://proyectoinventario.org/x-legislatura-la-asamblea-nacional-poder-popular-parlamento-cuba-2023-2028/

**Comment by pudo** [comment]
https://www.opensanctions.org/datasets/cu_inventario_legislatura/

**Comment by jbothma** [comment]
https://github.com/opensanctions/opensanctions/pull/356

**Comment by jbothma** [comment]
still needs to alert us in a year's time to check the maintenance situation and decide whether all positions can still automatically be set Current or not. https://github.com/opensanctions/opensanctions/pull/356#issuecomment-1684894698
