### ISSUE TITLE
last update/checked

### ISSUE THREAD

**Issue by hpvd** [opensanctions/opensanctions#344]
Looked into this interesting data for the first time via the search on the website.
What I'm missing in the shown results (within site and in popup), is an information when the data was last updated/checked/synced against official resources.
This would give a much better feeling about the quality of the data.

If one think this even further, there could be 3 dates within each data set for
- added to opensanction
- last update/change
- last check/sync

without this, one may be afraid, that there may be some pretty old datasets with db like in other projects... see:

![2023-08-07_14h36_49](https://github.com/opensanctions/opensanctions/assets/5681880/a3854dc2-33ba-48de-8582-8595f99ab617)

**Comment by pudo** [comment]
Thanks, that's a really good prod: we have these three fields in the data but aren't showing any of them on the site :) Easy fix.

**Comment by hpvd** [comment]
awsome! looking forward to it!

**Comment by pudo** [comment]
Added this to the entity page, definitely not winning any design prizes with that but it's visible now...
