### ISSUE TITLE
Moldova ban list delay issues

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#358]
![2023-08-17_13-13](https://github.com/opensanctions/opensanctions/assets/235801/26cf021a-7e58-45aa-a778-02050f8e8f89)
 I read these as "pending a court decision" as in "not active yet" which probably means we should not treat these as active yet.

Google translate:

> The execution of AAP decision no. 7/23 of 05/29/2023 according to the decision of the Chisinau Court, Rișcani seat of 07/07/2023, until the examination of the action in administrative litigation.

> The execution of AAP decision no. 8/23 of 29.05.2023 according to the decision of the Chisinau District Court Rîscani of 07.07.2023, until the court decision remains final.

no response to email to helpdesk@tender.gov.md 
messaged a Moldovan friend to help with interpretation.

**Comment by pudo** [comment]
This has been unresolved too long now. What if we just put the whole string in the sanction.reason prop? No need to lose sleep parsing this.
