### ISSUE TITLE
Cayman PEPs

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#364]
Ripe for automation:

- [Members of the House (legislativeassembly.ky) elected](http://www.legislativeassembly.ky/portal/page/portal/lglhome/members/elected-2021-2025) and the [previous term](http://www.legislativeassembly.ky/portal/page/portal/lglhome/members/previousmembers/2017-2021-Members)
- Under the Judicial Admin section has the various Judges: [Cayman Islands Judicial & Legal Website | An official website of the Cayman Islands Government – Cayman Islands Judicial & Legal Information Website](https://www.judicial.ky/judicial-administration)

Perhaps less ready for automation:

- Board of Directors for the regulator which is a statutory Authority [The Board of the Cayman Island Monetary Authority â€“ CIMA](https://www.cima.ky/the-board)
- List of government statutory authority and Government Companies: [Statutory Authorities | Cayman Islands Government](https://www.gov.ky/directory/statutory-authorities-and-government-companies)

**Comment by aivuk** [comment]
Questions:

> [Members of the House (legislativeassembly.ky) elected](http://www.legislativeassembly.ky/portal/page/portal/lglhome/members/elected-2021-2025) and the [previous term](http://www.legislativeassembly.ky/portal/page/portal/lglhome/members/previousmembers/2017-2021-Members)

We have only the following information:
  * Name 
  * Position (e.g. Premier)
  * Full position (e.g. Premier and Minister for Sustainability and Climate Resiliency and Finance & Economic Development Member of Parliament for Newlands)

you want for all positions? Speaker of Parliament, Premier, Deputy Premier, Cabinet Ministers, Ex Officio Members, and the scrolling down on the first link Elected Members > Government Backbench Members, Opposition Members and Independent Opposition Member. 

And we would add the Occupancy for the positions above terms.

>  Under the Judicial Admin section has the various Judges: [Cayman Islands Judicial & Legal Website | An official website of the Cayman Islands Government – Cayman Islands Judicial & Legal Information Website](https://www.judicial.ky/judicial-administration)

Are you interested only in the judges on https://www.judicial.ky/judicial-administration/judges, both current as retired ones? Which information to get? The only information that everyone have is the full name. Some have the nationality, some have the birth year, but there is no standard in how this information is displayed. Some are in a block of text and some are in a bullet list.

> Board of Directors for the regulator which is a statutory Authority [The Board of the Cayman Island Monetary Authority â€“ CIMA](https://www.cima.ky/the-board)

I only see the full name and a block of text with extra information on each individual director page (e.g. https://www.cima.ky/ms-helen-dombowsky)

> List of government statutory authority and Government Companies: [Statutory Authorities | Cayman Islands Government](https://www.gov.ky/directory/statutory-authorities-and-government-companies)

What to get, just the list of names, url's and tel? Some of the url's return 404 by the way.

**Comment by pudo** [comment]
Hey @aivuk :) I think if we pull in the judges and the House Assembly, that's enough for now. Names and positions will hopefully make this enough to reconcile with other data sources where we can then get more info (e.g. DOB). It's not great data, but we're playing for coverage here.

**Comment by jbothma** [comment]
hello!

- Assembly
  - Positions `Member of parliament`, `Minister of X`, `Minister of Y`, Speaker of Parliament, Premier, Deputy Premier
    - leader/deputy leader of opposition is nice to have but not essential
    - no need to capture their constituency
    - no need to capture back bench, ex officio, oppostion, independent, etc
  - yes occupancies to link the people and positions
-  Judiciary
  - Judges only, like Friedrich said
    - Only current, since it's not really shown in the data when they retired and we already know they're not current.
     - names, role.judge topic, sourceUrl is good yeah.

@pudo should judges get both the judge and the pep topic?

**Comment by pudo** [comment]
Done, closing.
