### ISSUE TITLE
Make sure this repository is eligible for hacktoberfest 

### ISSUE THREAD

**Issue by pescheck-bram** [opensanctions/opensanctions#378]
For several years, we've been active participants in Hacktoberfest. We're eager to include this repository in the event as well. By doing so, we anticipate an influx of merge requests. It's up to you to establish the criteria they should adhere to. Participating in Hacktoberfest can be a great way to not only contribute to the event but also to enrich this project with more data.

For more info (currently registrations are closed of course due it is only in Oktober):
https://hacktoberfest.com/

**Comment by pudo** [comment]
That's a cool idea! I added the required tag, and might try and throw some issues for more engineering-interesting problems into the tracker here :)

**Comment by pescheck-bram** [comment]
Great thank you :smile:
