### ISSUE TITLE
Add debarments from European EDES database

### ISSUE THREAD

**Issue by brawer** [opensanctions/opensanctions#418]
https://commission.europa.eu/strategy-and-policy/eu-budget/how-it-works/annual-lifecycle/implementation/anti-fraud-measures/edes/edes-database_en

**Comment by pudo** [comment]
I think if it's already in our [source planning sheet](https://docs.google.com/spreadsheets/d/1zHP91a-KT-MW-3s2Xb9-wPVhxTiPO1ZqJ90v4COswRY/edit#gid=0) we don't need to make an issue here separately, unless you plan to work on it :)
