### ISSUE TITLE
Add Slovenia debarments

### ISSUE THREAD

**Issue by brawer** [opensanctions/opensanctions#419]
Debarments from public procurement in Slovenia: https://erar.si/omejitve/
Already crawled by OCCRP Aleph: https://aleph.occrp.org/datasets/8867

**Comment by jbothma** [comment]
this is another source for this data https://podatki.gov.si/dataset/kpk-evidenca-poslovnih-subjektov-iz-35-clena-zintpk?resource_id=4214c5c6-f5f1-4a2e-9adb-87bad032ee40
