### ISSUE TITLE
Did Liechtenstein PDF out on us? 

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#430]
@brawer do I see this right that Liechtenstein removed the HTML version of the Sperren and replaced them with a PDF? We don't really have a solid PDF processing strategy in Zavod right now, so this leaves me at a loss a bit. 

https://www.llv.li/de/unternehmen/berichtspflichten-bewilligungen/grenzueberschreitende-dienstleistungen/entsendung-von-arbeitnehmern/sanktionsliste-gemaess-art.-7-abs.-4-entsg

**Comment by pudo** [comment]
Replaced with a static extract from before the switch. Crawler is now inactive :(

**Comment by brawer** [comment]
See [#1012 ](https://github.com/opensanctions/opensanctions/pull/1012) for an attempt at PDF processing.
