### ISSUE TITLE
Add Uruguay PEP list

### ISSUE THREAD

**Issue by atehe** [opensanctions/opensanctions#499]
PEP list from The National Secretariat for the Fight against Money Laundering and Financing of Terrorism (SENACLAFT) in Uruguay - https://www.gub.uy/secretaria-nacional-lucha-contra-lavado-activos-financiamiento-terrorismo/comunicacion/publicaciones/lista-pep

**Comment by jbothma** [comment]
https://github.com/opensanctions/opensanctions/pull/500
