### ISSUE TITLE
Call out system dependencies in install docs

### ISSUE THREAD

**Issue by fjuniorr** [opensanctions/opensanctions#504]
The [installation documentation](https://github.com/opensanctions/opensanctions/blob/main/zavod/docs/install.md#python-virtual-environment) currently states:

> zavod has an optional dependency on PyICU, a library related to the transliteration of names in other alphabets to the latin character set. This library is not installed by default because its configuration can be tricky. Consider following [the PyICU documentation](https://pypi.org/project/PyICU/) to install this library and achieve better transliteration results.

However, from my understanding, `pyicu` and `plyvel` are [required](https://github.com/opensanctions/opensanctions/blob/main/zavod/setup.py#L23) and their installation steps are not straightforward[^1]. It may be beneficial to highlight this early on, if this is indeed the case. A suggestion for revision could be:

> zavod has dependecies on PyICU - a library related to the transliteration of names in other alphabets to the latin character set - and Plyvel - a fast and feature-rich Python interface to LevelDB. The installation and configuration of both libraries can be complex due to system dependencies. Consider following the [PyICU](https://pypi.org/project/PyICU/) and [Plyvel](https://plyvel.readthedocs.io/en/latest/installation.html) documentation for the installation of both libraries.

Happy to open a PR with the suggested change.

[^1]: I'm on an M2 Mac and the tricky parts were related to https://github.com/Homebrew/homebrew-core/issues/36958 and https://github.com/wbolster/plyvel/issues/114#issuecomment-1162769419

**Comment by jbothma** [comment]
this PR would be very welcome, thank you!
