### ISSUE TITLE
Members of the Estonian Riigikogu don't have names

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#573]
**Describe the bug**

Members of Estonia's Riigikogu don't have names

**To Reproduce**

![Screenshot_2024-02-13_11-25-29](https://github.com/opensanctions/opensanctions/assets/235801/c94c8825-41e6-4455-bd37-a2fa691c2cdb)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dhdaines** [comment]
The name simply wasn't being applied to the entities!  I'll push a PR in a second.
