### ISSUE TITLE
We can get a lot of country/jurisdiction info from gb_coh_psc with country mappings

### ISSUE THREAD

**Issue by jbothma** [opensanctions/opensanctions#584]
**Is your feature request related to a problem? Please describe.**

Lots of country and jurisdiction warnings https://data.opensanctions.org/datasets/20240214/gb_coh_psc/issues.json

**Describe the solution you'd like**

Mappings for them, and perhaps making the warnings visible

**Describe alternatives you've considered**

none

**Additional context**

![Screenshot 2024-02-21 at 09 36 16](https://github.com/opensanctions/opensanctions/assets/235801/54216d37-6eb1-454c-be2b-902dcb5542e0)

**Comment by jbothma** [comment]
Maybe not worth it since only a small subset of these entities are ultimately exported by https://www.opensanctions.org/datasets/ext_gb_coh_psc/ - let's see what things look like when the next full run of gb_coh_psc finishes.

**Comment by ChrisjanWust** [comment]
Hey @jbothma 

It's me!! Hope you're doing great my fellow South African.

Is this still an issue for you guys? If so, do you have more examples of problematic issues JSON files?

**Comment by jbothma** [comment]
hey @ChrisjanWust! Very nice to hear from you!

data will always be dirty :D So we'll always be dealing with new dataset issues. 

Most of our issue logs get listed here https://www.opensanctions.org/issues/ when they're nonempty. Raw company registers like this aren't listed there cos it's just not worth cleaning them perfectly if we only end up [using a small fraction of the data](https://www.opensanctions.org/docs/enrichment/). I can help you find those if you're interested though!

I'll close this item since we won't be fixing this here.
