### ISSUE TITLE
Work to be done on NSDC crawler

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#623]
I've done most of the work on the NSDC crawler, however we still need to check if we have to fetch the `actions` and `restrictions` for all subjects, as documented here: https://api-drs.nsdc.gov.ua/swagger/#/Sanctions%20Registry%20subjects%20%2F%20%D0%A0%D0%B5%D1%94%D1%81%D1%82%D1%80%20%D0%BF%D1%96%D0%B4%D1%81%D0%B0%D0%BD%D0%BA%D1%86%D1%96%D0%B9%D0%BD%D0%B8%D1%85%20%D1%81%D1%83%D0%B1'%D1%94%D0%BA%D1%82%D1%96%D0%B2/SubjectsController_restrictions

We also need to map out the remaining attribute fields.

**Comment by pudo** [comment]
The format from NSDC contains an array for each entity called "attributes". These are super messy, you can see the current handling code here: https://github.com/opensanctions/opensanctions/blob/main/datasets/ua/nsdc_sanctions/crawler.py#L153-L168 and the related mappings here: https://github.com/opensanctions/opensanctions/blob/main/datasets/ua/nsdc_sanctions/ua_nsdc_sanctions.yml#L100 

There's still a fair bit of detail to be extracted there, but doing this with Google Translate is painful since a lot of it is ambiguous.

**Comment by pudo** [comment]
That sounds like a great increment, and I appreciate stopping when it's getting absurd. Do you want to put up a PR?

**Comment by dchaplinsky** [comment]
Wrapping it up

**Comment by dchaplinsky** [comment]
https://github.com/opensanctions/opensanctions/pull/898

**Comment by pudo** [comment]
Closing this for now as we're just seeing the regular amount of failure out of this one.
