### ISSUE TITLE
Czech company data crawler is broken

### ISSUE THREAD

**Issue by pudo** [opensanctions/opensanctions#758]
Seems like the old source site, http://wwwinfo.mfcr.cz/ares/ares.html.en is down. 

There's a new portal here, which documents an API: https://www.mfcr.cz/cs/ministerstvo/informacni-systemy/ares

Should we ask them for bulk data?

**Comment by pudo** [comment]
Open data commentary: https://ares.gov.cz/stranky/otevrena-data 
Catalog: https://data.gov.cz/dataset?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00006947%2F4e7b6c4003ae1079dda2b7a56c93d248

**Comment by jbothma** [comment]
Also https://www.czso.cz/csu/czso/registr-ekonomickych-subjektu-otevrena-data

**Comment by pudo** [comment]
Fixed based on a suggested remedy by @atehe.
